### ISSUE TITLE
A v1.0 release is needed

### ISSUE THREAD

**Issue by dgsb** [konsorten/go-windows-terminal-sequences#1]
This package is now a dependency of logrus for its windows build.
With the recent introduction of modules and  in order to ensure build reproductibility we would need a release of the v1.0 api definition.
Can we have some visibility on an estimation date of such a release ?

**Comment by dgsb** [comment]
@fkollmann do you mind looking at this issue?

**Comment by fkollmann** [comment]
Thanks for the reminder! Please see tag v1.0.1 (5c8c8bd35d3832f5d134ae1e1e375b69a4d25242)
